### PR TITLE
Gazebo quadrotor drivers

### PR DESCRIPTION
**Pull request by DanielYS**
He añadido los drivers para cuadricópteros en Gazebo 5.0 en la carpeta gazeboserver/plugins.
También he añadido las primeras versiones de los mundos para la competición de programación de drones.

### CODE REVIEW

**Comment by rocapal** [comment]
Thanks Daniel for your help!

Firstable, use English for your messages. Successfully we have international collaborators and it could be nice they also can understand you :-)

As I have seen, the dependencies of gazebo in JdeRobot is
```
PKG_CHECK_MODULES(GAZEBO QUIET gazebo<=2.0.0 )
```
If we want support Gazebo 5.0 with our components, first we need to create the dependencies correctly. Could you add the dependencies for gazebo 5.0 in Deps/gazebo/ ?

**Comment by abhi-kumar** [comment]
@rocapal to add dependencies for gazebo 5.0 will it be sufficient to change "PKG_CHECK_MODULES(GAZEBO QUIET gazebo<=2.0.0 )" to 

"PKG_CHECK_MODULES(GAZEBO QUIET gazebo<=5.0 ) "

Regards,
Abhishek

**Comment by DanielYS** [comment]
Hello.

I've already changed the CMakeLists.txt. The Gazebo version is 5.0.1, which is the one I've used to test the quadrotor drivers.

Regards

**Comment by fqez** [comment]
Hi,

just a note. If you install gazebo5 from packages nowadays the version which is installed is gazebo 5.1.0 not gazebo 5.0.1 just for your information.

Regards.

**Comment by rocapal** [comment]
Thanks @DanielYS !

**Pull request merged**
