### PR TITLE
EasyProxy

### PR DESCRIPTION
**Pull request by varhub**
# EasyProxy

*#261 fork*

Inspired by #261 I realized my own fork because two major issues:
1. it should be a function instead a class (constructor + getter)
2. template must be always placed into header. Otherways template capacity is lost (and only available for already compiled ones).

Initial idea was realized here:
- https://github.com/jderobot-varribas/JdeRobot/blob/createProxy-frivas-fork/src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/proxies.hpp
- https://github.com/jderobot-varribas/JdeRobot/commit/eb9d6ed9c91f139598fe4af9f794879b3a531dc8

Final version (0.9.3.1) recover class approach by implement proxy pattern. So class is transparent to user and code.

*It took me 3 hours to figure out how to do operator=()* At least this time avoid me to use this fucking weird and ugly call:
`camera->get()->getImageData()`

Sound familiar? same as colorspacesmm: `colorspaces::ImageRGB8::FORMAT_RGB8.get()->name`
Ask question at #248

## What includes?
* proper exception raising
* transparent wrapper (proxy pattern)
* if scoped logic
* and so on

### CODE REVIEW

**Comment by chanfr** [comment]
Hi,
good job Victor. Everything looks pretty nice. I only have one comment. Can you leave the part of the proxy handler under the existing library (handlers). We have two features here. The simplification of the use of generic proxies and the simplification of the configuration of the components. 

Can you create two pull requests one for each new feature?

**Comment by varhub** [comment]
Please, read and pay a minimal atention before post.

Perhaps your fault is due I forgot the link to release https://github.com/jderobot-varribas/libeasyiceconfig/releases/tag/0.9.3.1

**Comment by chanfr** [comment]
This is an open pull request and I've just reviewing the pull request. If you check which files have been included into the pull request you can see:

src/stable/components/introrob_qt/robot/sensors.cpp
src/stable/components/introrob_qt/robot/sensors.h
src/stable/libs/easyiceconfig_cpp/CMakeLists.txt
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/EasyProxy.h
src/stable/libs/easyiceconfig_cpp/include/easyiceconfig/proxies.hpp
src/stable/libs/easyiceconfig_cpp/src/tests/test_proxy.cpp

And that is exactly what i was talking about. The proxies.hpp is inside easyiceconfig. If this pull request is erroneous of it a discussion please move it or close it.

**Comment by varhub** [comment]
I understood, you expect that I split my PR in two parts, proxies.hpp and rest. Isn't it?

**Comment by chanfr** [comment]
Yes that was the idea.

**Comment by varhub** [comment]
Ok, therefore let me known how do it because I can't see how to split it.
This is what contains actual PR:

* 41a90b9603c8d8890ddbf022b1e4f51d7837e2d0:
  - proxies.hpp - core feature. This is all, no more dependencies neither .so
  - EasyProxy.h - alias to pack it inside EasyIce (namespace flattering)
  - test_proxy.cpp - a test that show how it works and almost every use cases
* a68ce921ccaf1f0fe5a4905d67b89cf63d632491:
  - sensors.h/sensors.cpp - an example of how to inject it into current components; just like #251

I qeued @fqez to complete sensors.cpp and actuators.cpp to get a feedback

By the way, there are 3 reasons because I put proxies.hpp at EasyIceConfig:
  - Half of simplification is related to ice config file (the other half to exception handling)
  - I already tweak EasyIceConfig cmakelist to export library include dir and allow transparent `include_directories(${easyiceconfig_INCLUDE_DIRS})` without additional effort
  - jderobotHandlers is simply bad constructed, but this is another story

**Comment by varhub** [comment]
@fqez, commit reviewed
But there is a misconception. Good news are that I did it also, so you simply copy my fault.

actuatos variable (proxy) do not requires to be wrapped because createProxy returns a plain proxy.
Therefore, assign to the wrapper is not totally correct because exception will never be initialized (worse scenario: proxy is null, but exception is catched outside. If other piece of code checks nullity and print exception... segfault (null)).
For this usage one must use copy constructor or avoid wrapper.

I will fix it in both files. At least it can be used as part of manual

**Comment by varhub** [comment]
For me it is done, but I need @fqez and @chanfr feedback.
Lib manual entry created at: http://jderobot.org/Libs#EasyProxy_.28easyiceconfig.29

*Ready to be merged*

**Comment by chanfr** [comment]
Just for your reasons I think that we have to split the functionality into two different libraries. EasyIceConfig have two different functionalities:
1- Reduces the complexity of use and find configuration files.
2- Reduces the code to write while writing a new "client side" application.

I can't see any reason to put this two features together. The first one is for all the applications and the second one only tor the client side. The first one is to reduce the configuration complexity and the second is just to reduce code writing. 

I don't agree with your affirmation about "jderobotHandlers is simply bad constructed" this lib only uses the existing library structure of jderobot libraries.

**Comment by varhub** [comment]
If you wish, take proxies.hpp and place it at "optimal" place.
By the way, why jderobotHandlers is not splited? (refering to recorder)

PS: you should try to fulfit introrob_qt with your handler and see the differences

**Comment by chanfr** [comment]
Right,
jderobot handler only has functionality related to reduce the code writing on the client side, so I can't see any to split. As jderobotHandler has been created to reduce to code writing I've just included a handler of recorder to not duplicate on each recorder client the conversion between an enumerated type and a string.

**Comment by varhub** [comment]
Thanks all for break this PR.

I officially leave active development and support.

**Pull request closed without merging**
