### PR TITLE
Pull request for issue #211

### PR DESCRIPTION
**Pull request by reysam93**
This pull request should close the issue #211. It solves some bugs (of the python and c++ components) and adds new functionality, mostly about generating a runtime gui for the python component.

### CODE REVIEW

**Comment by fqez** [comment]
Hi Samuel,

I cannot make it run :( Can you post here the instructions to make it works? I've downloaded one some of your examples:

ardronepy1.xml does not generate any code, it says there is some empty sections that shouldn't be.
ardronepy1.1.xml generates the python code, and it works for Ardrone1 (without showing the GUI), but not for ArDrone2 (I tried changing the .cfg file also).
try2.xml works well but it also not show any GUI at execution. 

The steps I followed are:

1- download your xml example.
2- execute visualHFSM
3- open the xml file (Archive->Open)
4- Generate python code
5- Close visualHFSM
6- execute the generated code ./xxxxx.py

Am I missing something?

Thanks!

**Comment by reysam93** [comment]
Hi,

Yes, there are some steps you have to follow for preparing the environment,
if not the imports wont find the files. I am in the metro now, I send it to
you as soon as I get home and will also put them in the man Page.

Sorry I forgot to tell you.

**Comment by fqez** [comment]
Oh I forgot to mention that I also did the steps listed in instructionspy.txt file from your repo. But I will wait for your feedback!

Thanks!

**Comment by reysam93** [comment]
If you have done those steps it should be fine. Your only problem is that
it doesn't display the gui? Because it is disabled by default. For showing
it you have to run it with the argument --displaygui=true

Also some examples are old and the code could not be fine, I would
recommend you try it with try3.py, as it is the last example I have done
and the more complex (the actions it does are simple but has many nodes and
automatas)

2016-02-10 14:54 GMT+01:00 Francisco Pérez <notifications@github.com>:

**Comment by fqez** [comment]
Ok now it works with displaygui flag! Sadly you commited the taxi models in this same branch... my fault for the delay. I will merge this because I tested the models too and all of them works, but try to work with different branches in the future. If you don't know how to do it, tell me and I sill teach you some tricks.
Very cool all the models by the way :)

Good job!

**Comment by reysam93** [comment]
I didn't know the pull request would be the same, I was trying to create a new one. I only know a bit about branches, but actually I have never use it for pull request as I normally am the only one working in my repository, so I could use some advices :D 
By the way, I have deleted the models from TeachingRobotics.

Thanks!

**Comment by fqez** [comment]
Perfect! good job! tell me by email if you want some tips about branches. Cheers!

**Pull request merged**
