### PR TITLE
Renewing color tuner (colorTuner old image format #281)

### PR DESCRIPTION
**Pull request by 02081994**
Whole component has been changed.
This time cv::Mat has been used everywhere.

### CODE REVIEW

**Comment by 02081994** [comment]
I have deleted those 2 lines and add the other 2 and have replaced every cvSize with cv::Size or cv::Mat(image.size(), image.type()). 

Thank You for pointing these out. I'll try to avoid such mistakes in future.

**Comment by varhub** [comment]
I can't see deletion of every cv.h and highgui.h (viewer.h for example)
Did you forget to push it?

**Comment by 02081994** [comment]
I have removed both (cv.h and highgui.h) from all the concerned files.

**Comment by varhub** [comment]
Thanks ^^

**Comment by 02081994** [comment]
Your Welcome :')

**Comment by fqez** [comment]
Ok tested and working! Thanks for your contribution!!

**Pull request merged**
