### PR TITLE
Fix #139: Stable uav.

### LINKED ISSUE #139: Moving uav_viewer component from 'testing' to 'stable'
Moving uav_viewer component from src/testing/components to src/stable/components.

### PR DESCRIPTION
**Pull request by shady-cs15**
New pull request for moving uav_viewer from testing branch to stable branch.
@rocapal Please take a look at this.

### CODE REVIEW

**Comment by rocapal** [comment]
@shady-cs15 thanks. I have some problems with the compilation process because a header is not found.
```c++
/tmp/JdeRobot/src/stable/components/uav_viewer/gui/attitudeindicator.cpp:4:25: fatal error: qwt_polygon.h: The file doesn't exist
 #include <qwt_polygon.h>
```
Could you check in which debian packages is this header? We should check this header in the Deps directory as well.

**Comment by rocapal** [comment]
You can check it the output of cmake in: http://pastebin.com/ARQRgpap
BTW, I'm using Debian Sid.

**Comment by shady-cs15** [comment]
@rocapal Yes It requires this package to be installed: libqwt5-qt4-dev
I have mentioned it in my wiki http://jderobot.org/Chakraborty-colab#uav_viewer
In my machine it is in /usr/include/qwt-qt4.
I see that in your cmake output Lines 154 & 155, it says that both the libraries and the include directories have been found.

**Comment by rocapal** [comment]
@shady-cs15 I think that the problem is the version of the library. I have libqwt-dev (6.0.0-1.2) installed in my system. May be we have to check the version of this library, and enable the components just if the  version of libqwt5 library is 5 (<6). What do you think?

**Comment by shady-cs15** [comment]
Sure. I'll make the changes soon. But, can you let me know if qwt_polygon.h header file is in /usr/include/qwt-qt4 or not.

**Comment by rocapal** [comment]
@shady-cs15 No it doesn't. In fact, I have the /usr/include/qt4/ folder, but the header is not there.

If I install the libqwt5-qt4-dev pacakge (removing the libqwt-dev 6.0), I found the library here:
```c++
$ dpkg -L libqwt5-qt4-dev | grep qwt_polygon.h
/usr/include/qwt-qt4/qwt_polygon.h
```
If I do that, the compilation of the component works fine.

So, I would suggest check the version of the libqwt library and you should disable the compilation of the component just in case the version 6 of the library is installed.

**Comment by shady-cs15** [comment]
@rocapal you were right about the version issue. The versions are mentioned in include_dir/qwt_global.h. I have added support for version 5 checking using a regular expression match in the latest commit. https://github.com/shady-cs15/JdeRobot/commit/2616e07849dae87046f039251b7f3530835bc762.

Let me know if things are alright.

**Comment by rocapal** [comment]
@shady-cs15 it's perfect now :-) I'm going to pass this pull request.
Thanks for your contribution.

**Pull request merged**
