### PR TITLE
Drone worlds for gsoc

### PR DESCRIPTION
**Pull request by shady-cs15**
Add drone worlds and models for gsoc.
1. ArDrone_simple-gsoc.world
2. ArDrone_texture-gsoc.world
3. grass_plane.model

@rocapal Please a take a look at this. :) 
Let me know if there are any further changes to be made.

### CODE REVIEW

**Comment by rocapal** [comment]
@shady-cs15 Did you remove the branch?

$ git pull https://github.com/shady-cs15/JdeRobot.git drone-worlds-gsoc
fatal: Couldn't find remote ref drone-worlds-gsoc

**Comment by shady-cs15** [comment]
yes I think so. Updating it shortly.

**Comment by shady-cs15** [comment]
@rocapal  If it is alright I will make the pull request again when I have updated the models from polaris ranger ev to car models.

**Comment by rocapal** [comment]
@shady-cs15 Perfect! Thanks!

**Pull request merged**
