### PR TITLE
Issue #104: Memory leak

### PR DESCRIPTION
**Pull request by DanielYS**
The callback function was reserving memory for the image everytime it was called. Now memory allocation is carried out in the load method.

### CODE REVIEW

**Comment by rocapal** [comment]
@DanielYS I have checked the source code and I didn't see where you delete the image variable. In the Load() method you always create a new image, but you never destroy it. Also the image variable should be a private member of the class (not public). Could you check it before accept this pull request?

Thanks.

**Comment by andresjhe** [comment]
I have tried it and it solves the memory leak problem. 
I confirm this solves the memory leak.

**Comment by fqez** [comment]
Yes, that solves this issue, I've just tested it.

**Comment by rocapal** [comment]
Thanks guys for confirm it!

**Pull request merged**
