### PR TITLE
Fix #OpenCV_Fixes - OpenCV3.0_Compatibility_Fixes

### PR DESCRIPTION
**Pull request by abhi-kumar**
In this fix, I have made changes to various files to make the source compatible with a combination of Opencv-3.0.0 and Ubuntu-14.04. Changes will not affect the proper working in lower ubuntu and opencv versions. {Contribution from GSoC applicant email id : abhishek4273@gmail.com}

### CODE REVIEW

**Comment by rocapal** [comment]
Hi!
Firstable than you for your efforce. We appreciate so much your help. Secondly, when you have in your mind a huge change like this, please first use the mail list o github issue to tell everybody what is your idea. In this case, opencv 3.0 is still beta. We know that it's working well but we prefer don't integrate any library in alpha/beta state.

Also you pull request is so big. 105 files were modified and it's very dificult to test all the components. Did you do that? Because in otherwise some components can be broken even the compilation works.

I think it's better wait for a release version of opencv 3.0 and modify and check carefully each JdeRobot component.

**Comment by abhi-kumar** [comment]
@rocapal as instructed lets continue the discussion related to OpenCV 3.0.0 here. Opencv's 3.0.0 is almost similar to its stable version 2.9, just with a few minor changes in syntax of basic commands like cvtColor(used in our source code a lot of times), then module representation like backgroundSubtractor. The modules in 2.4 are updated in 2.9 with new feature additions which we can make use of on a very large scale. The above changes to the JdeRobot source code are keeping in mind the same. In our code we are dependant on OpenCV1 libraries like cv.h, highgui.h, which in turn has very less support over Mat representation of images and runs over IplImage. Mat representation would make our dependencies more memory efficient. Also if the system has OpenCV installed, it will tend to resort libraries from the system rather than the libraries provided by us, that is why I have included a few changes in cmakelists.txt files by providing an option between the system libraries and the ones present in the source code.

**Comment by abhi-kumar** [comment]
@rocapal I did test all the changes applied and then only I have asked for the merge request. Could you please tell me as to how can I proceed with this in a more formal way?

**Comment by rocapal** [comment]
Before ask about merge request, you should check that your changes compile correctly (I assume you did that) and for every components you modified you should check that they work fine in execution time. I mean, if you make changes in openniServer o giraffeClient you should test that these components running correctly with your changes. For that, you have to create small pull request of components that you have checked correctly. Did you check giraffeClient component is working fine?
As you said, opencv 3.0 has a lot of improvements, but is still beta. When opencv will be released as stable version, we need to schedule how is the best way to migrate to this new version. Because the change is huge. 

Also, you have added opencv dependencies in components like "ns" or "logger", which it doesn't make sense. The first one is a naming service and the second one is a log library. Either has opencv functionality/dependency. I'm afraid we can not accept this patch for the moment.

**Comment by abhi-kumar** [comment]
@rocapal The one with the ns and logger surprised me too, because only after adding that I was able to compile the source, otherwise I was getting errors like "imread is not a component of cv", "line is not a component of cv". Is is possible that I pull up each component's request one by one rather than putting up everything at once, i.e., first going up with library colorspaces, then geometry and then so on,. because of pre-installed version of opencv 2.9 on my laptop I was not able to compile the source without the changes made. So is it fine if I go introducing every issue one by one and lets discuss over each part and add accordingly?

**Pull request closed without merging**
