### PR TITLE
Fix #152: Algorithms dir for uav_viewer

### LINKED ISSUE #152: Visual processing for counting cars in uav_viewer
Develop algorithms for counting vehicles in uav_viewer component.
Add support for enabling/disabling this feature.

### PR DESCRIPTION
**Pull request by shady-cs15**
@rocapal All visual processing algorithms are in the algorithms dir. (Still developing on them).
In cfg files, UAVViewer.algo variable parameter is created (set 0 by default). Visual processing occurs only when this variable is set.

This requires an additional dependency: cvBlobs.
For now the check for finding cvBlobs is in uav_viewer/CMakeLists.txt
Will move it to /Deps directory if required.

Compilation and installation of cvBlob:
https://code.google.com/p/cvblob/wiki/HowToInstall

### CODE REVIEW

**Comment by rocapal** [comment]
@shady-cs15 I have some comments for you:Remember that you should not use the CMakeList.txt of the component to find

**Comment by shady-cs15** [comment]
Sorry I didn't notice that before. The latest changes have taken the cvBlobs in src/stable/libs/visionlib into account.

**Comment by rocapal** [comment]
@shady-cs15 We are close :-) You also have to change the following include 
```
#include <cvblob.h>
```
For do a real test, try to remove your cvBlob library that it is installed in your system.
You should use the path that you have in our project 'visionlib/cvBlob/cvblob.h'. Also you should add the ${LIBS_DIR} into the include directories. Please, check the rgbdCalibrator component that uses cvBlob library as well.

**Comment by shady-cs15** [comment]
@rocapal Thanks for pointing out this issue. Changes made in the last 2 commits. Hope it works now. :)

**Pull request closed without merging**
