### PR TITLE
quadrotor2 extra features

### PR DESCRIPTION
**Pull request by varhub**
*Related to #229 iter II*

### CODE REVIEW

**Comment by varhub** [comment]
Here you are test to check it: https://github.com/jderobot-varribas/quadrotor2_tests

**Comment by fqez** [comment]
Well, I've just tested this PR, and it works almost fine. There is a little issue with the dual Pose3D results. The issue is that the real Z pose and the sonar given Z pose doesn't match by almost 2 meters, according to the tests you uploaded [here](https://github.com/jderobot-varribas/quadrotor2_tests)

Here you are an image showing that "problem", you can see the <b>real</b> and <b>sonar</b> Z pose are not the same. I really don't know if this is intended or not so, am I missing something?

Bad z pose

I had no problem with the rest of your changes. Good job! :)

**Comment by fqez** [comment]
It has something to do with #273 right?

**Comment by varhub** [comment]
Yes, related to #273 

By the way, what happens when you change altitude of robot? (2m, 4m, 10m, 15m, etc)
Sonar should stop at 3m except you increase sensor's range (L382?)
Change it to 7 and retry above altitude values.

**Comment by varhub** [comment]
I just see **test_dualpose** and yes, this was the expected output ;)

**Comment by fqez** [comment]
Oh ok, I get it. Sonar range limit is 3m only, fine. Thanks! I'm merging this right now :)

**Pull request merged**
